# -*- coding: utf-8 -*-
"""Programmatic SEO ページデータ（第1弾: 11ページ）。
actor URL は index.html / Apify プロフィールで実在確認済みのもののみ使用する。
"""

PROFILE = ("Browse all Japanese market scrapers",
           "https://apify.com/fruitful_quintessence")

A_MANDARAKE = ("Mandarake Auction Scraper",
               "https://apify.com/fruitful_quintessence/mandarake-auction-scraper")
A_DLSITE = ("DLsite Scraper",
            "https://apify.com/fruitful_quintessence/dlsite-scraper")
A_MERCARI = ("Mercari Japan Search Scraper",
             "https://apify.com/fruitful_quintessence/mercari-japan-search-scraper")
A_YAHOO = ("Yahoo! Auctions Japan Scraper",
           "https://apify.com/fruitful_quintessence/yahoo-auctions-japan-scraper")
A_GOONET = ("goo-net Japan Used Cars Nationwide Inventory",
            "https://apify.com/fruitful_quintessence/goo-net-japan-used-cars-nationwide-inventory")

# 2026-10-11 実在確認済み（HTTP 200・非deprecated）。MLIT Reinfolib の公式取引価格データ。
A_MLIT = ("Japan Real Estate Transaction Prices API",
          "https://apify.com/fruitful_quintessence/mlit-japan-property-prices")

PAGES = [
    {
        "slug": "japan-market-data-api",
        "title": "Japan Market Data API — Resale & Auction Scrapers",
        "desc": "Pay-per-result APIs for Japanese resale, auction and collectible marketplaces. Clean JSON from Apify: prices, condition, images and URLs in JPY.",
        "h1": "Japan Market Data API",
        "intro": [
            "Japanese resale markets are large, fragmented and almost entirely published in Japanese. The price signal sits behind search pages that are rendered client-side, paginated, and rate-limited — which is why most price-tracking projects stall on the data layer before they reach the interesting part.",
            "These scrapers run on the Apify cloud and return one clean JSON record per listing: item name, current price in JPY, condition, image URL, listing URL and timestamps. You pay per result, so a full sweep of a niche catalogue typically costs less than a dollar.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_name", "Listing title exactly as the marketplace publishes it."),
            ("current_price_jpy", "Asking price in Japanese yen, unformatted."),
            ("condition", "Seller-declared condition grade where the marketplace exposes one."),
            ("item_url", "Canonical listing URL for reprocessing or manual review."),
            ("image_url", "Primary listing image, hot-linkable for catalogues."),
            ("sold_at", "Timestamp for sold/ended listings on auction sources."),
        ],
        "use_cases": [
            "Build a price index for a specific collectible category before deciding what stock to source.",
            "Feed an LLM agent with live Japanese pricing instead of stale training data.",
            "Monitor a watchlist of items and alert when the asking price drops below a threshold.",
            "Export a category-wide dataset to CSV for spreadsheet review or BI tools.",
        ],
        "faq": [
            ("Which marketplaces are covered?",
             "The current set is Mandarake auction (figures, manga, trading cards), DLsite (doujin, voice, ASMR), Mercari Japan (C2C listings), and an official MLIT real estate transaction price API. The publisher page lists exactly what is live right now, so check it before planning a pipeline."),
            ("Do I need a Japanese IP address?",
             "No. The scrapers run on Apify infrastructure and handle the regional access themselves; you only consume the dataset."),
            ("How is billing calculated?",
             "Per result returned, roughly $0.002 per item, so cost scales with how much data you actually pull rather than a flat monthly seat."),
        ],
        "related": ["japan-resale-market-data", "japan-price-monitoring-api",
                    "japan-market-data-mcp-server", "japan-market-data-csv-export"],
    },
    {
        "slug": "mandarake-auction-data-api",
        "title": "Mandarake Auction Data API — Figures, Manga, Cards",
        "desc": "Scrape Mandarake auction listings into JSON: figure, manga and trading card prices in JPY with condition, images and listing URLs.",
        "h1": "Mandarake Auction Data API",
        "intro": [
            "Mandarake is one of the reference price sources for second-hand Japanese collectibles. Its auction floor is where rare figures, vintage manga runs and unopened trading card boxes settle at their true market clearing price — not the optimistic number a seller types into a marketplace listing.",
            "This scraper turns Mandarake auction pages into structured JSON. For anyone pricing a collection, sourcing stock, or building a valuation model, it replaces manual page-by-page checking with a dataset you can query.",
        ],
        "actor": A_MANDARAKE,
        "fields": [
            ("item_name", "Auction lot title, including series and edition markers."),
            ("current_price_jpy", "Current bid or hammer price in yen."),
            ("condition", "Grade where the lot publishes one."),
            ("item_url", "Direct lot URL."),
            ("image_url", "Lot photograph."),
            ("sold_at", "Auction end timestamp for closed lots."),
        ],
        "use_cases": [
            "Valuation: compare a graded figure's asking price against what auction lots actually cleared at.",
            "Sourcing: find categories where the auction clearing price sits below overseas retail.",
            "Catalogue building: pull images and titles for a storefront or database.",
        ],
        "faq": [
            ("Is this the same as general marketplace scraping?",
             "No. Auction data carries an end timestamp and a realised price, which is what distinguishes a valuation signal from an asking price."),
            ("Can I filter by keyword or category?",
             "Runs are driven by the search terms you supply, so you scope a run to the series, maker or category you care about."),
            ("What about sold lots?",
             "Closed lots keep their end timestamp, so you can separate realised prices from still-live listings."),
        ],
        "related": ["anime-figure-price-data", "japan-trading-card-price-data",
                    "japan-collectibles-price-api", "japan-auction-price-data"],
    },
    {
        "slug": "anime-figure-price-data",
        "title": "Anime Figure Price Data — Japanese Market in JSON",
        "desc": "Track anime figure prices from Japanese second-hand and auction sources. Structured JSON with grade, price in JPY, images and listing URLs.",
        "h1": "Anime Figure Price Data",
        "intro": [
            "Figure prices are volatile in a way that is hard to see from a single storefront. A scale figure that sat at retail for a year can double once a rerun window closes, and the market often splits by grade: sealed, opened-displayed, and box-damaged move at very different prices.",
            "Collecting prices from Japanese second-hand and auction sources side by side is what makes that spread visible. The scrapers return graded listings with yen prices, so you can group by condition instead of comparing sealed against opened.",
        ],
        "actor": A_MANDARAKE,
        "fields": [
            ("item_name", "Figure name with series, scale and edition detail as listed."),
            ("current_price_jpy", "Price in yen at the time of the run."),
            ("condition", "Grade, so sealed and opened stock can be separated."),
            ("image_url", "Product photograph for quick visual verification of the edition."),
            ("item_url", "Listing URL for forwarding to a buyer or a colleague."),
        ],
        "use_cases": [
            "Detect rerun-driven price cliffs by sampling the same search weekly.",
            "Decide whether an opened copy at a discount is genuinely cheaper than a sealed one.",
            "Build an internal price guide for a shop that buys and resells figures.",
        ],
        "faq": [
            ("Do prices include the Japanese consumption tax?",
             "Prices are recorded as published by the source. Treat them as the listed number and handle tax rules in your own pipeline."),
            ("Can I track a specific series only?",
             "Yes — a run is scoped by the search terms you provide, so you can follow one series, one maker, or one character."),
            ("How often should I re-run?",
             "For volatile collectibles a weekly sample is usually enough to catch a rerun effect; daily is only worth it if you are actively trading."),
        ],
        "related": ["mandarake-auction-data-api", "japan-trading-card-price-data",
                    "japan-collectibles-price-api", "japan-secondhand-market-data"],
    },
    {
        "slug": "japan-trading-card-price-data",
        "title": "Japan Trading Card Price Data — Bulk Listings in JSON",
        "desc": "Collect Japanese trading card prices in bulk: box, single and sealed product listings with yen prices, condition, images and source URLs.",
        "h1": "Japan Trading Card Price Data",
        "intro": [
            "The Japanese card market moves differently from the English-language one. Sealed boxes, single cards and promo distributions are often priced first in Japan, and an English-market repricing tends to follow rather than lead it.",
            "Sampling Japanese listings in bulk gives you the leading edge of that series. The scraper returns one record per listing with the price, condition and image URL, so you can chart a card's Japanese ask against its overseas price.",
        ],
        "actor": A_MANDARAKE,
        "fields": [
            ("item_name", "Card, box or product name as listed."),
            ("current_price_jpy", "Asking or cleared price in yen."),
            ("condition", "Grade for singles where published."),
            ("image_url", "Listing image, useful for spotting reprints and counterfeit tells."),
            ("item_url", "Source URL."),
        ],
        "use_cases": [
            "Arbitrage research: compare the Japanese ask against the English-market ask for the same card.",
            "Sealed product tracking: follow how box prices move as supply tightens.",
            "Inventory review: batch-price a collection from a single search sweep.",
        ],
        "faq": [
            ("Can I get sold prices for cards?",
             "Auction-sourced records keep an end timestamp, so closed lots can be separated from live asks."),
            ("Is grading data included?",
             "Where the source publishes a grade it is captured in the condition field; the scrapers do not perform their own grading."),
            ("Does this cover English-language cards?",
             "Coverage follows the Japanese marketplaces, which list both Japanese and imported product."),
        ],
        "related": ["mandarake-auction-data-api", "anime-figure-price-data",
                    "japan-collectibles-price-api", "resale-arbitrage-japan"],
    },
    {
        "slug": "dlsite-scraper-api",
        "title": "DLsite Scraper API — Doujin Market Data in JSON",
        "desc": "Scrape DLsite listings into structured JSON: price in JPY, category, circle, rating and product URL for doujin, voice and ASMR catalogues.",
        "h1": "DLsite Scraper API",
        "intro": [
            "DLsite is the largest marketplace for independently produced Japanese digital works: doujin games, comics, voice dramas, ASMR and illustration sets. Its catalogue is enormous, categorised in Japanese, and refreshed constantly, which makes manual market research impractical beyond a handful of titles.",
            "This scraper converts DLsite listing data into JSON so a whole category can be sampled at once. That makes it usable for trend research, recommendation features, or simply understanding what is actually selling inside a niche.",
        ],
        "actor": A_DLSITE,
        "fields": [
            ("item_name", "Work title as published."),
            ("current_price_jpy", "Price in yen, including discounted campaigns where present."),
            ("category", "Genres and tags attached to the work."),
            ("item_url", "Product page URL."),
            ("image_url", "Cover image URL."),
        ],
        "use_cases": [
            "Trend research: find which tags and genres are gaining listings within a category.",
            "Catalogue tooling: enrich an internal database with titles, covers and prices.",
            "Price tracking: watch how campaign discounts change the effective price of a work.",
        ],
        "faq": [
            ("Does it cover physical doujin goods?",
             "Coverage follows DLsite's own catalogue, which is digital-first; physical sourcing is covered by the Mandarake scraper instead."),
            ("Are ratings and review counts included?",
             "Whatever the listing page publishes — rating, review count, circle name — can be captured alongside the title and price."),
            ("Is the content adult-only?",
             "DLsite hosts both all-ages and adult sections. You scope a run by the search terms and sections you supply; the scraper returns what the catalogue shows."),
        ],
        "related": ["doujin-market-data", "asmr-audio-price-data",
                    "japan-market-data-api", "japan-secondhand-market-data"],
    },
    {
        "slug": "doujin-market-data",
        "title": "Doujin Market Data — Japanese Indie Catalogue in JSON",
        "desc": "Structured data on the Japanese doujin market: titles, circles, genres and yen prices from DLsite, returned as JSON for research and tooling.",
        "h1": "Doujin Market Data",
        "intro": [
            "The doujin market is a genuine independent publishing economy, and unlike most indie scenes its catalogue is centralised enough to measure. Genres shift fast, a single popular release can define a season, and pricing follows a campaign rhythm rather than a fixed retail model.",
            "Having the catalogue in structured form turns those impressions into observations: how many works a tag is gaining, what a genre's typical price band looks like, and which circles publish repeatedly.",
        ],
        "actor": A_DLSITE,
        "fields": [
            ("item_name", "Release title."),
            ("current_price_jpy", "Listed price in yen."),
            ("category", "Genre and tag set — the main axis for market analysis."),
            ("item_url", "Product URL for verification."),
            ("image_url", "Cover art."),
        ],
        "use_cases": [
            "Genre analysis: measure how listing volume concentrates across tags over time.",
            "Publisher tracking: identify circles that release consistently within a niche.",
            "Marketplace features: power a category browser or recommendation list with fresh data.",
        ],
        "faq": [
            ("Is this legal to use commercially?",
             "The scraper returns catalogue metadata — titles, prices, genres, URLs. Whether a downstream use is permissible depends on your own product and the source's terms; the data itself is product metadata, not creative content."),
            ("How deep does a sweep go?",
             "Depth is set by the search scope you configure, from a narrow tag to a broad category sample."),
            ("Can I join this with external sales data?",
             "The output is plain JSON with stable field names, so it merges easily with your own tables."),
        ],
        "related": ["dlsite-scraper-api", "asmr-audio-price-data",
                    "japan-market-data-api", "japan-price-monitoring-api"],
    },
    {
        "slug": "asmr-audio-price-data",
        "title": "ASMR & Voice Work Price Data — Japan Market JSON",
        "desc": "Sample Japanese ASMR and voice-drama pricing from DLsite as structured JSON: titles, circles, tags, yen prices and cover images.",
        "h1": "ASMR & Voice Work Price Data",
        "intro": [
            "Voice and ASMR works are the fastest-moving segment of the Japanese digital doujin market. Releases arrive in themed waves, discount campaigns are frequent, and the effective price of a work changes several times during its commercial life.",
            "Sampling that catalogue as data makes it possible to separate a genuinely popular tag from one that simply has many listings, and to see which circles sustain output across multiple seasons.",
        ],
        "actor": A_DLSITE,
        "fields": [
            ("item_name", "Work title."),
            ("current_price_jpy", "Price after any active campaign."),
            ("category", "Tags describing content type, scenario and cast."),
            ("item_url", "Product page."),
            ("image_url", "Cover art."),
        ],
        "use_cases": [
            "Campaign tracking: measure how often a catalogue discounts and by how much.",
            "Tag research: identify which content tags are gaining releases.",
            "Storefront tooling: build category pages from live metadata instead of hand-curated lists.",
        ],
        "faq": [
            ("Are the audio files themselves scraped?",
             "No. The scraper collects catalogue metadata only — titles, prices, tags, URLs and cover images."),
            ("Can I filter by voice actor or circle?",
             "A run is scoped by the search terms you supply, and circle information published on the listing can be captured."),
            ("How reliable are tag counts?",
             "Treat them as a snapshot of listing volume, not sales. Listing counts measure supply; pairing with price movement gives a better read on demand."),
        ],
        "related": ["dlsite-scraper-api", "doujin-market-data",
                    "japan-price-monitoring-api", "japan-market-data-for-ai-agents"],
    },
    {
        "slug": "mercari-japan-price-data",
        "title": "Mercari Japan Price Data — C2C Listings as JSON",
        "desc": "Scrape Mercari Japan listings into JSON: real-time prices in JPY, condition, seller data and URLs from Japan's largest C2C marketplace.",
        "h1": "Mercari Japan Price Data",
        "intro": [
            "Mercari Japan is the single best proxy for what Japanese consumers actually pay for second-hand goods. Listings turn over quickly, prices are negotiated by individual sellers, and the same item can sit at wildly different asks depending on how urgently someone wants it gone.",
            "Because the market is C2C, the spread is the signal. A single sweep shows the current price band for an item; a weekly sweep shows which direction it is moving.",
        ],
        "actor": A_MERCARI,
        "fields": [
            ("item_name", "Listing title."),
            ("current_price_jpy", "Asking price in yen."),
            ("condition", "Seller-declared condition."),
            ("item_url", "Listing URL."),
            ("image_url", "Primary image."),
        ],
        "use_cases": [
            "Buy-side research: establish a realistic price band before making an offer.",
            "Sell-side pricing: check what comparable items currently ask before listing your own stock.",
            "Arbitrage screening: surface Japanese listings that sit well below overseas equivalents.",
        ],
        "faq": [
            ("Is sold data available?",
             "Mercari's public listings expose asking prices. For realised prices, the auction sources (Mandarake, Yahoo! Auctions) carry end timestamps."),
            ("Can I search by keyword and category?",
             "Yes — runs are scoped by the search terms you provide, and the marketplace category can be recorded with each record."),
            ("How fresh is the result set?",
             "Each run captures the state of the catalogue at that moment, so freshness is a function of how often you run it."),
        ],
        "related": ["mercari-price-monitoring", "japan-auction-price-data",
                    "resale-arbitrage-japan", "japan-secondhand-market-data"],
    },
    {
        "slug": "mercari-price-monitoring",
        "title": "Mercari Price Monitoring — Automated Price Drop Alerts",
        "desc": "Monitor Mercari Japan listings on a schedule and alert on price drops. JSON output with yen prices, condition and listing URLs.",
        "h1": "Mercari Price Monitoring",
        "intro": [
            "A price watch on a C2C marketplace is only useful if it runs on a schedule. Individual sellers cut prices when an item does not move, and those cuts are the moment a marginal item becomes a good buy.",
            "Running the Mercari scraper on a recurring schedule gives you a time series rather than a snapshot. Diff two runs by listing URL and the price changes fall out directly.",
        ],
        "actor": A_MERCARI,
        "fields": [
            ("item_name", "Listing title, used as the human key in alerts."),
            ("current_price_jpy", "Price at the time of each run — diff this field."),
            ("condition", "Condition, so a price drop on worse condition is not a false positive."),
            ("item_url", "Stable key for diffing runs and linking the alert."),
        ],
        "use_cases": [
            "Alert when a watched item falls below your threshold price.",
            "Track how long an average listing takes to sell at different price points.",
            "Feed a dashboard that shows price history for a shortlist of items.",
        ],
        "faq": [
            ("How do I diff runs?",
             "Match records on item_url across runs and compare current_price_jpy; a lower value on the later run is a price drop."),
            ("Can I limit monitoring to specific items?",
             "Scope the run to the search terms that identify your watchlist so the result set stays small and cheap."),
            ("What should the schedule be?",
             "Daily is a sensible default; increase the frequency only for items where a few hours of lead time has real value."),
        ],
        "related": ["mercari-japan-price-data", "japan-price-monitoring-api",
                    "japan-price-drop-alerts", "japan-market-data-csv-export"],
    },
    {
        "slug": "yahoo-auctions-japan-data",
        "title": "Yahoo! Auctions Japan Data — Listings & Sold Prices",
        "desc": "Scrape Yahoo! Auctions Japan: live listings and realised auction prices in JPY with condition, images and URLs, returned as JSON.",
        "h1": "Yahoo! Auctions Japan Data",
        "intro": [
            "Yahoo! Auctions is where a great deal of Japanese second-hand stock actually changes hands. Unlike a fixed-price marketplace, it publishes an outcome: the auction ends, and the closing bid is a realised price rather than an aspiration.",
            "That makes it the most useful source for valuation work. Realised prices collected over months give you a defensible estimate of what an item is worth, which is a different question from what someone is currently asking.",
        ],
        "actor": A_YAHOO,
        "fields": [
            ("item_name", "Auction title."),
            ("current_price_jpy", "Current bid or closing price in yen."),
            ("condition", "Declared condition where published."),
            ("item_url", "Auction URL."),
            ("image_url", "Item photograph."),
            ("sold_at", "Auction end timestamp — the marker of a realised price."),
        ],
        "use_cases": [
            "Valuation: build a realised-price series instead of relying on asking prices.",
            "Sourcing: find stock that is underbid because the listing is poorly titled or photographed.",
            "Market timing: identify categories where closing prices are trending up.",
        ],
        "faq": [
            ("Can I separate live from finished auctions?",
             "Yes. Records with an end timestamp in the past are closed lots; the price attached to them is the realised price."),
            ("Do I need a Yahoo! account?",
             "No. The scraper runs server-side and you consume the resulting dataset."),
            ("Is shipping cost included?",
             "Only where the listing publishes it; treat shipping as a separate field in your own margin model."),
        ],
        "related": ["japan-auction-price-data", "mercari-japan-price-data",
                    "resale-arbitrage-japan", "mandarake-auction-data-api"],
    },
    {
        "slug": "japan-auction-price-data",
        "title": "Japan Auction Price Data — Realised Prices in JSON",
        "desc": "Collect realised auction prices from Japanese marketplaces as structured JSON. Separate closed lots from live asks and analyse true market value.",
        "h1": "Japan Auction Price Data",
        "intro": [
            "Asking price and market value are different numbers, and conflating them is the most common mistake in resale research. Auctions resolve that ambiguity: when a lot closes, the winning bid is evidence.",
            "Collecting realised prices from a Japanese auction floor over a period of weeks gives a defensible valuation base — including the tail of lots that sold cheap because demand, not the item, was missing that week. The Mandarake auction actor is the auction source used here; it returns each lot with a price and an end timestamp, which is what turns a listing into evidence.",
        ],
        "actor": A_MANDARAKE,
        "fields": [
            ("item_name", "Lot title."),
            ("current_price_jpy", "Bid or closing price in yen."),
            ("condition", "Grade where published."),
            ("sold_at", "End timestamp — the field that makes the record a realised price."),
            ("item_url", "Lot URL for audit."),
        ],
        "use_cases": [
            "Valuation: compute a median realised price per item rather than an average asking price.",
            "Outlier detection: find lots that closed far below the category norm.",
            "Reporting: produce a price trend chart that a non-specialist audience will accept.",
        ],
        "faq": [
            ("How many closed lots do I need for a stable estimate?",
             "For a niche collectible, roughly a dozen realised prices usually stabilise a median; thin categories need a longer window."),
            ("Can I exclude outliers?",
             "Yes — realised prices come as individual records with a timestamp, so median and trimmed-mean approaches are straightforward."),
            ("Do the scrapers cover both auction and fixed-price sources?",
             "Yes. Mandarake provides the auction floor with closing timestamps, while Mercari provides fixed-price C2C asks, so you can decide which side your analysis should rest on."),
        ],
        "related": ["mandarake-auction-data-api", "japan-resale-market-data",
                    "resale-arbitrage-japan", "japan-secondhand-market-data"],
    },
]
