# -*- coding: utf-8 -*-
"""Programmatic SEO ページデータ（第2弾: 11ページ）。
actor URL は index.html / Apify プロフィールで実在確認済みのもののみ使用する。
"""

from seo_pages_1 import (PROFILE, A_MANDARAKE, A_DLSITE, A_MERCARI, A_YAHOO, A_GOONET, A_MLIT)

PAGES = [
    {
        "slug": "japan-used-car-price-data",
        "title": "Japan Used Car Price Data — Nationwide Inventory JSON",
        "desc": "Scrape nationwide Japanese used car inventory from goo-net: price in JPY, model year, mileage, spec and dealer data, returned as JSON.",
        "h1": "Japan Used Car Price Data",
        "intro": [
            "Japan's used car market is unusually transparent for its size. Nationwide dealer inventory is published with mileage, model year, grade and a listed price, which means a price benchmark can be assembled from data rather than from a handful of phone calls.",
            "This scraper collects that inventory into structured records. For exporters, importers and dealers, it turns 'what should this car cost' into a query against thousands of current listings.",
        ],
        "actor": A_GOONET,
        "fields": [
            ("item_name", "Vehicle description including make, model and grade."),
            ("current_price_jpy", "Listed price in yen."),
            ("condition", "Grade and condition indicators where published."),
            ("item_url", "Listing URL."),
            ("image_url", "Vehicle photograph."),
        ],
        "use_cases": [
            "Export sourcing: benchmark a model across the whole country before committing to a purchase.",
            "Import pricing: check whether an asking price abroad is supported by the Japanese market.",
            "Depreciation analysis: sample the same model across model years to estimate a depreciation curve.",
        ],
        "faq": [
            ("Does the data include mileage?",
             "Yes — mileage, model year, transmission and specification detail are captured where the listing publishes them."),
            ("Can I restrict to one prefecture?",
             "Runs are scoped by the search parameters you supply, so you can narrow by region, make or price band."),
            ("Is auction-grade data included?",
             "This actor covers dealer inventory. Auction sheet grading is a separate data source and a different workflow."),
        ],
        "related": ["japan-used-car-market-data", "japan-market-data-api",
                    "japan-price-monitoring-api", "japan-market-data-csv-export"],
    },
    {
        "slug": "japan-used-car-market-data",
        "title": "Japan Used Car Market Data — Model & Grade Trends",
        "desc": "Analyse the Japanese used car market with structured inventory data: model-level pricing, grade spread, mileage distribution and dealer listings.",
        "h1": "Japan Used Car Market Data",
        "intro": [
            "Used car pricing is not one market — it is a set of markets segmented by model, grade, mileage band and region. Two listings that look identical in a headline can differ substantially once those factors are separated, which is exactly what spreadsheet work on a few examples cannot reveal.",
            "Collecting inventory at nationwide scale lets you segment properly. The result is a defensible view of where a model's realistic price sits and how wide the spread around it is.",
        ],
        "actor": A_GOONET,
        "fields": [
            ("item_name", "Make, model and grade."),
            ("current_price_jpy", "Listed price in yen."),
            ("condition", "Grade and mileage indicators."),
            ("item_url", "Listing URL for verification."),
        ],
        "use_cases": [
            "Segment a model by grade and mileage band to find where the real price sits.",
            "Track how a popular model's price band shifts across a season.",
            "Support a purchase decision with a nationwide comparison rather than local quotes.",
        ],
        "faq": [
            ("How large a sample do I need?",
             "For a mainstream model, a nationwide sweep typically yields enough listings to build a price band; niche models may need repeated sampling."),
            ("Can this be exported for analysis?",
             "Yes — records are JSON and convert directly to CSV or a dataframe."),
            ("Does it cover motorcycles?",
             "This actor targets used car inventory; the publisher page lists the full set of marketplace scrapers available."),
        ],
        "related": ["japan-used-car-price-data", "japan-market-data-api",
                    "japan-resale-market-data", "japan-market-data-csv-export"],
    },
    {
        "slug": "japan-resale-market-data",
        "title": "Japan Resale Market Data — Multi-Source Price Signal",
        "desc": "Combine Japanese resale, auction and collectible marketplace data into one price signal. JSON records with JPY prices from five live scrapers.",
        "h1": "Japan Resale Market Data",
        "intro": [
            "Single-source price data is easy to collect and easy to misread. A figure that looks expensive on one marketplace may be the cheapest copy on another, and a category that seems to be rising may simply have shifted from auction listings to fixed-price ones.",
            "Pulling from several Japanese sources and keeping the records separate lets you see the spread instead of a single number: auctions for realised prices, C2C marketplaces for consumer asks, dedicated collectible floors for specialist grades.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_name", "Product title as published by the source."),
            ("current_price_jpy", "Price in yen, consistent across sources."),
            ("condition", "Source-published grade."),
            ("item_url", "Source listing URL — also identifies which marketplace a record came from."),
            ("sold_at", "Present for auction sources; absent for live fixed-price listings."),
        ],
        "use_cases": [
            "Triangulate a fair price from auction outcomes plus live asks.",
            "Detect when a category is migrating between marketplaces.",
            "Build a category report that separates supply-side listings from demand-side outcomes.",
        ],
        "faq": [
            ("How do I combine sources without double counting?",
             "Keep the source URL with each record; identical items rarely share a URL, and deduplication by title plus price band handles the rest."),
            ("Should I trust asking prices?",
             "Use them to see supply and competition. Use auction end prices when you need a defensible value."),
            ("Does one run cover all marketplaces?",
             "They are separate actors, so you decide which sources to run and at what frequency."),
        ],
        "related": ["japan-market-data-api", "japan-auction-price-data",
                    "japan-secondhand-market-data", "resale-arbitrage-japan"],
    },
    {
        "slug": "japan-price-monitoring-api",
        "title": "Japan Price Monitoring API — Scheduled Price Tracking",
        "desc": "Run scheduled scrapes against Japanese marketplaces and diff runs to track price movement. JSON output with yen prices and stable listing URLs.",
        "h1": "Japan Price Monitoring API",
        "intro": [
            "Price monitoring is a diff problem. You need the same field, measured repeatedly, keyed on something stable. Japanese marketplace listings are well suited to this because the listing URL persists while the price changes.",
            "Running the scrapers on a schedule and matching records on item_url produces a time series per item with very little engineering. From there, alerting is a comparison, and reporting is a chart.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_url", "Stable key for matching records across runs."),
            ("current_price_jpy", "The field you diff."),
            ("condition", "Guards against false positives when condition differs."),
            ("sold_at", "Marks a listing as ended so it can be retired from the watchlist."),
        ],
        "use_cases": [
            "Alert when a watched item's price falls below a threshold.",
            "Chart the price history of a shortlist across several weeks.",
            "Retire sold items automatically using the end timestamp.",
        ],
        "faq": [
            ("What schedule makes sense?",
             "Daily covers most shortlists; hourly is only worth it for genuinely fast-moving stock."),
            ("How do I detect an item disappearing?",
             "A key present in an earlier run and absent from a later one has ended or been delisted — treat both as 'no longer available'."),
            ("Will re-running cost the same each time?",
             "Billing is per result, so keeping the search scope tight keeps the recurring cost small."),
        ],
        "related": ["japan-price-drop-alerts", "mercari-price-monitoring",
                    "japan-market-data-csv-export", "japan-market-data-api"],
    },
    {
        "slug": "resale-arbitrage-japan",
        "title": "Resale Arbitrage Japan — Cross-Border Price Spread Data",
        "desc": "Find resale arbitrage by comparing Japanese marketplace prices with overseas asking prices. Structured JSON with yen prices and listing URLs.",
        "h1": "Resale Arbitrage Japan",
        "intro": [
            "Arbitrage between Japan and Western markets has a long history in collectibles, cameras and cars, and it survives because the information is genuinely hard to assemble. Prices are published in Japanese, on marketplaces with different catalogue conventions, and the interesting spread is often invisible from a search result page.",
            "Systematic screening requires structured data on both sides. The Japanese side is what these scrapers provide: prices in yen with condition, images and URLs, in a format you can join to your own comparison table.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_name", "Title to match against your overseas reference table."),
            ("current_price_jpy", "Japanese price in yen for conversion and margin maths."),
            ("condition", "Critical — arbitrage margins collapse if the cheaper copy is in worse condition."),
            ("item_url", "Listing URL for manual verification before committing capital."),
        ],
        "use_cases": [
            "Screen a category for items where the Japanese ask is well below overseas demand.",
            "Verify a specific listing's condition and photos before committing to a purchase.",
            "Track the spread on a shortlist over time to see when it opens and closes.",
        ],
        "faq": [
            ("Does this include shipping or duties?",
             "No. Those are your own costs and must be added before treating a spread as profit."),
            ("How do I avoid false positives?",
             "Compare condition and edition, not just titles. Reissues and box damage are the usual causes of a spread that looks too generous."),
            ("Is this suitable for fixed-price or auction sourcing?",
             "Both. Auctions give realised prices, C2C marketplaces give quick-turnover asks."),
        ],
        "related": ["japan-resale-market-data", "japan-trading-card-price-data",
                    "japan-auction-price-data", "japan-market-data-api"],
    },
    {
        "slug": "japan-market-data-mcp-server",
        "title": "Japan Market Data MCP Server — Live Prices for AI Agents",
        "desc": "Expose Japanese marketplace scrapers as MCP servers so Claude, Cursor and other assistants can query live Japanese price data as a tool call.",
        "h1": "Japan Market Data MCP Server",
        "intro": [
            "An assistant asked about current Japanese prices will answer from training data, which means it is wrong the moment a rerun hits or a seller cuts a price. The fix is to give the agent a tool that returns live listings instead of a recollection.",
            "Several of these scrapers are exposed as MCP servers, so a compatible client — Claude Desktop, Cursor, or your own harness — can call them directly. The agent requests a search, receives JSON records, and reasons over current data.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_name", "Product title returned to the agent."),
            ("current_price_jpy", "Live price the agent quotes, with the run timestamp as context."),
            ("condition", "Lets the agent distinguish sealed from opened stock."),
            ("item_url", "Citation URL so a human can verify the agent's claim."),
        ],
        "use_cases": [
            "Let an agent answer 'what does this figure go for in Japan right now' with live data.",
            "Give a shopping or sourcing assistant an authoritative Japanese price check.",
            "Ground a valuation workflow in retrievable listings rather than model memory.",
        ],
        "faq": [
            ("Which clients are supported?",
             "Any MCP-compatible client. The actors are listed on the publisher page, and the actor description indicates the MCP endpoint."),
            ("Can the agent write data back?",
             "No. The server exposes read-only scraping tool calls; it does not modify any marketplace."),
            ("How do I keep responses cheap?",
             "Scope the search terms narrowly and cap the number of results the tool returns to the agent."),
        ],
        "related": ["japan-market-data-for-ai-agents", "japan-market-data-api",
                    "japan-price-monitoring-api", "japan-collectibles-price-api"],
    },
    {
        "slug": "japan-market-data-csv-export",
        "title": "Japan Market Data to CSV — Spreadsheet-Ready Exports",
        "desc": "Export Japanese marketplace data to CSV or a dataframe: one row per listing with JPY price, condition, images and URLs from Apify datasets.",
        "h1": "Japan Market Data to CSV",
        "intro": [
            "Not every analysis needs a pipeline. A surprising amount of useful work happens in a spreadsheet: sorting a category by price, filtering to a condition grade, and eyeballing where the outliers sit.",
            "Apify datasets export directly to CSV, Excel and JSON, so the practical workflow is to run a scoped search, export the rows, and open the file. For recurring work, the same dataset feeds Python or a BI tool without changing anything upstream.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_name", "Column for sorting and filtering."),
            ("current_price_jpy", "Numeric column, safe to sort and aggregate in a spreadsheet."),
            ("condition", "Filter column for separating grades."),
            ("item_url", "Reference column for opening the original listing."),
            ("image_url", "Image column for visual review."),
        ],
        "use_cases": [
            "Hand a category overview to a colleague who works in spreadsheets, not JSON.",
            "Filter a category to one grade and sort by price to find the cheapest acceptable copy.",
            "Archive a dated export as a price snapshot for later comparison.",
        ],
        "faq": [
            ("Which formats are available?",
             "Datasets export to CSV, JSON, Excel and other common formats directly from the run's dataset view."),
            ("Do I need to write code?",
             "No. A run can be started from the Apify console and the dataset downloaded from the UI; code is optional for automation."),
            ("How do I compare two snapshots?",
             "Export both, match rows on item_url, and compare the price column — the same diff approach as an API-driven monitor."),
        ],
        "related": ["japan-price-monitoring-api", "japan-market-data-api",
                    "japan-real-estate-price-data", "japan-resale-market-data"],
    },
    {
        "slug": "japan-collectibles-price-api",
        "title": "Japan Collectibles Price API — Figures, Cards, Doujin",
        "desc": "Structured price data for Japanese collectibles: figures, trading cards and doujin works with JPY prices, grades, images and listing URLs.",
        "h1": "Japan Collectibles Price API",
        "intro": [
            "Collectible pricing rewards specificity. A generic 'used figure' price is close to useless, while a price for one character, one scale, one grade and one edition is immediately actionable — and that granularity only comes from listing-level data.",
            "These scrapers return listing-level records across the Japanese collectible floors, so you can slice by series, grade and marketplace instead of relying on an aggregate that averages away the difference.",
        ],
        "actor": A_MANDARAKE,
        "fields": [
            ("item_name", "Title carrying series, scale and edition markers."),
            ("current_price_jpy", "Price in yen."),
            ("condition", "Grade — the main price-setting variable for collectibles."),
            ("item_url", "Listing URL."),
            ("image_url", "Photo for edition verification."),
        ],
        "use_cases": [
            "Build a graded price guide for a figure or card series.",
            "Spot the price effect of a rerun announcement within days.",
            "Price an incoming collection acquisition before making an offer.",
        ],
        "faq": [
            ("Which collectible categories are covered?",
             "Figures, manga, trading cards and doujin works are covered across the Mandarake and DLsite scrapers; the publisher page lists each actor."),
            ("Can I compare across marketplaces?",
             "Yes — run more than one actor and keep the source URL with each record."),
            ("Is grading data standardised?",
             "Grades follow each source's own convention, so treat them as source-published labels rather than a unified scale."),
        ],
        "related": ["anime-figure-price-data", "japan-trading-card-price-data",
                    "mandarake-auction-data-api", "doujin-market-data"],
    },
    {
        "slug": "japan-secondhand-market-data",
        "title": "Japan Secondhand Market Data — C2C & Specialist Floors",
        "desc": "Secondhand Japanese marketplace data in JSON: C2C listings, specialist collectible floors and auction outcomes with JPY prices and links.",
        "h1": "Japan Secondhand Market Data",
        "intro": [
            "Japan's secondhand market is not one marketplace. Consumer C2C traffic sits on one platform, specialist collectibles on dedicated floors, and used vehicles on a dealer inventory network — and each publishes a different slice of the truth.",
            "Treating them as one dataset makes the structure visible: where supply is concentrated, which categories trade on auctions rather than fixed prices, and how quickly listings turn over in each.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_name", "Listing title as published."),
            ("current_price_jpy", "Price in yen."),
            ("condition", "Source-declared condition."),
            ("item_url", "Listing URL, which also identifies the source marketplace."),
            ("sold_at", "End timestamp for auction records."),
        ],
        "use_cases": [
            "Map which marketplaces dominate a given category.",
            "Decide whether a category is better sourced via auctions or fixed-price listings.",
            "Build a turnover estimate from how quickly listings disappear between runs.",
        ],
        "faq": [
            ("Can I tell which marketplace a record came from?",
             "Yes — the source listing URL identifies it, and you can carry a source field through your own pipeline."),
            ("Does this cover physical retail?",
             "Coverage is limited to the marketplaces each actor targets; traditional retail chains without public inventory pages are not included."),
            ("How should I handle duplicate items?",
             "Deduplicate on title plus price band, and keep the URL so a human can break ties."),
        ],
        "related": ["japan-resale-market-data", "mercari-japan-price-data",
                    "japan-real-estate-price-data", "japan-market-data-api"],
    },
    {
        "slug": "japan-price-drop-alerts",
        "title": "Japan Price Drop Alerts — Automated Marketplace Watchlist",
        "desc": "Build automated price drop alerts for Japanese marketplaces. Scheduled JSON scrapes with stable listing URLs make run-to-run diffs trivial.",
        "h1": "Japan Price Drop Alerts",
        "intro": [
            "The value of a price alert is entirely in its latency. An item that drops below your threshold today is actionable; the same information next week is a footnote, because someone else has already bought it.",
            "Because each run returns records keyed on the listing URL, a scheduled scrape plus a single comparison gives you an alert that fires the day the price moves. No browser automation on your side, no fragile selectors to maintain.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_url", "The stable key your alert logic matches on."),
            ("current_price_jpy", "Compared against the previous run and your threshold."),
            ("condition", "Prevents alerting on a price drop caused by worse condition."),
            ("sold_at", "Retires listings that have ended."),
        ],
        "use_cases": [
            "Email or chat alert when a watched listing falls under your target price.",
            "Weekly digest of the largest price reductions in a category.",
            "Feed a sourcing bot that reacts automatically to qualifying drops.",
        ],
        "faq": [
            ("How do I avoid alert spam?",
             "Alert only on a drop larger than a set percentage, and suppress repeats by storing the last-alerted price per URL."),
            ("Can I watch several marketplaces at once?",
             "Yes — run the relevant actors on the same schedule and merge their records before diffing."),
            ("What about items that reappear?",
             "Keep history keyed on URL. If a URL reappears after ending, note the gap rather than treating it as a continuous price series."),
        ],
        "related": ["japan-price-monitoring-api", "mercari-price-monitoring",
                    "japan-market-data-api", "japan-market-data-csv-export"],
    },
    {
        "slug": "japan-market-data-for-ai-agents",
        "title": "Japanese Market Data for AI Agents & LLM Tools",
        "desc": "Give AI agents live Japanese pricing instead of stale training data. Read-only MCP tool calls return structured JSON listings in JPY.",
        "h1": "Japanese Market Data for AI Agents",
        "intro": [
            "Language models are confidently wrong about current prices, and Japanese marketplace prices move faster than any training cutoff. The practical fix is not a better model but a better tool: let the agent query a live source and cite what it found.",
            "These scrapers return compact, structured records that fit comfortably in a model context — title, price in yen, condition, URL — which is exactly the shape an agent needs to answer a pricing question and show its evidence.",
        ],
        "actor": PROFILE,
        "fields": [
            ("item_name", "Short, model-friendly title field."),
            ("current_price_jpy", "Numeric price the agent can quote and compare."),
            ("condition", "Lets the agent caveat its answer by grade."),
            ("item_url", "Citation the agent can surface so a human verifies the claim."),
        ],
        "use_cases": [
            "Ground a sourcing assistant in live Japanese prices instead of paraphrase.",
            "Let a research agent compare Japanese and overseas pricing in one call.",
            "Give a shopping agent a verifiable price check before it recommends a purchase.",
        ],
        "faq": [
            ("Do the agents need a special framework?",
             "No — MCP is the integration surface, and any compatible client can call the server as a tool."),
            ("How do I stop the agent inventing prices?",
             "Require a listing URL with every price it reports; a claim without a citation is discarded."),
            ("Is the response size manageable?",
             "The returned records are small. Capping the result count per tool call keeps the context budget predictable."),
        ],
        "related": ["japan-market-data-mcp-server", "japan-market-data-api",
                    "japan-price-monitoring-api", "japan-collectibles-price-api"],
    },
    {
        "slug": "japan-real-estate-price-data",
        "title": "Japan Real Estate Price Data — MLIT Transaction API",
        "desc": "Query official Japanese real estate transaction prices from the MLIT Reinfolib API. Structured JSON with price, area, location, building info and zoning across 47 prefectures.",
        "h1": "Japan Real Estate Price Data",
        "intro": [
            "Japanese property listing portals show asking prices, which is a different number from what transactions actually cleared at. For any serious valuation work the useful figure is the recorded transaction price, and in Japan that data is published by the government through the MLIT Reinfolib dataset.",
            "This actor queries that dataset and returns structured JSON: transaction price, floor area, location, building information and zoning, covering all 47 prefectures. Because the underlying source is the official land and property transaction record rather than a broker's listing, it stands up as evidence in an appraisal or investment memo.",
        ],
        "actor": A_MLIT,
        "fields": [
            ("transaction price", "Recorded price for a completed transaction, in yen."),
            ("area", "Land or floor area for the transaction, as recorded."),
            ("location", "Prefecture, municipality and district metadata."),
            ("building info", "Structure, use and construction details where recorded."),
            ("zoning", "District and zoning classification tied to the parcel."),
        ],
        "use_cases": [
            "Build a comparable-sales set for an appraisal instead of relying on asking prices.",
            "Screen which municipalities transact at the strongest price per square metre.",
            "Feed a property dashboard with official figures that a client can verify at source.",
        ],
        "faq": [
            ("Where does the data come from?",
             "The national MLIT Reinfolib transaction price dataset, queried through the actor. It is official government-published transaction data rather than portal listings."),
            ("How current are the records?",
             "The underlying dataset is updated periodically by the ministry, so treat the returned set as the latest published batch rather than real-time sale prices."),
            ("Can I filter by prefecture or period?",
             "Yes — the run is scoped by the query parameters you supply, which is what makes prefecture-level and period-level analysis practical."),
        ],
        "related": ["japan-market-data-api", "japan-market-data-csv-export",
                    "japan-price-monitoring-api", "japan-resale-market-data"],
    },
]
